'use client';

/**
 * Project Guidance Panel Component (Slice 2C: Project Genesis)
 *
 * Displays AI-generated, project-specific guidance for each workspace section.
 * Guidance is generated by the PROJECT_GENESIS job based on Blueprint v2.
 *
 * Reference: blueprint.md §7 - Section Guidance
 *
 * Usage:
 *   <ProjectGuidancePanel projectId={projectId} section="data" />
 */

import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
  Sparkles,
  CheckCircle2,
  Circle,
  ChevronDown,
  ChevronUp,
  AlertTriangle,
  Lightbulb,
  Loader2,
  ExternalLink,
  Database,
  RefreshCw,
  Info,
  Clock,
  Zap,
} from 'lucide-react';
import { cn } from '@/lib/utils';
import { Button } from '@/components/ui/button';
import {
  useSectionGuidance,
  useGenesisJobStatus,
  useTriggerProjectGenesis,
  useRegenerateProjectGuidance,
} from '@/hooks/useApi';
import type {
  GuidanceSection,
  GuidanceChecklistItem,
  GuidanceRecommendedSource,
  GuidanceSuggestedAction,
} from '@/lib/api';

// Section display names
const SECTION_DISPLAY_NAMES: Record<GuidanceSection, string> = {
  data: 'Data Sources',
  personas: 'Personas',
  rules: 'Rules & Assumptions',
  run_params: 'Run Parameters',
  event_lab: 'Event Lab',
  scenario_lab: 'Scenario Lab',
  calibrate: 'Calibration',
  backtest: 'Backtesting',
  reliability: 'Reliability',
  run: 'Run Center',
  predict: 'Predictions',
  universe_map: 'Universe Map',
  reports: 'Reports & Exports',
};

interface ProjectGuidancePanelProps {
  /** Project ID */
  projectId: string;
  /** Current section key */
  section: GuidanceSection;
  /** Callback when an action is clicked */
  onActionClick?: (action: GuidanceSuggestedAction) => void;
  /** Callback when checklist item is toggled */
  onChecklistToggle?: (item: GuidanceChecklistItem, completed: boolean) => void;
  /** Additional CSS classes */
  className?: string;
  /** Whether to show collapsed by default */
  defaultCollapsed?: boolean;
  /** Whether to show provenance info */
  showProvenance?: boolean;
}

export function ProjectGuidancePanel({
  projectId,
  section,
  onActionClick,
  onChecklistToggle,
  className,
  defaultCollapsed = false,
  showProvenance = true,
}: ProjectGuidancePanelProps) {
  const [expanded, setExpanded] = useState(!defaultCollapsed);

  // Fetch guidance for this section
  const { data: guidance, isLoading, error, refetch } = useSectionGuidance(
    projectId,
    section
  );

  // Genesis job status for showing regeneration progress
  const { data: genesisStatus } = useGenesisJobStatus(projectId, {
    enabled: !!projectId,
  });

  // Mutations
  const triggerGenesis = useTriggerProjectGenesis();
  const regenerateGuidance = useRegenerateProjectGuidance();

  // Calculate checklist progress
  const checklistItems = guidance?.checklist || [];
  const completedCount = checklistItems.filter((item) => item.completed).length;
  const totalCount = checklistItems.length;
  const progressPercent = totalCount > 0 ? Math.round((completedCount / totalCount) * 100) : 0;

  // Handle regenerate button
  const handleRegenerate = async () => {
    try {
      await regenerateGuidance.mutateAsync(projectId);
    } catch (err) {
      // Error handled by mutation
    }
  };

  // Handle trigger genesis (if no guidance exists)
  const handleTriggerGenesis = async () => {
    try {
      await triggerGenesis.mutateAsync({ projectId });
    } catch (err) {
      // Error handled by mutation
    }
  };

  // Loading state
  if (isLoading) {
    return (
      <div className={cn('bg-white/5 border border-white/10 p-4', className)}>
        <div className="flex items-center gap-2 text-gray-400">
          <Loader2 className="h-4 w-4 animate-spin" />
          <span className="text-sm font-mono">Loading project guidance...</span>
        </div>
      </div>
    );
  }

  // Genesis job in progress
  if (genesisStatus?.has_job && genesisStatus.status === 'running') {
    return (
      <div className={cn('bg-gradient-to-r from-purple-500/10 to-cyan-500/10 border border-purple-400/30 p-4', className)}>
        <div className="flex items-center gap-3">
          <div className="relative">
            <Sparkles className="h-5 w-5 text-purple-400" />
            <motion.div
              className="absolute inset-0 rounded-full bg-purple-400/20"
              animate={{ scale: [1, 1.5, 1], opacity: [0.5, 0, 0.5] }}
              transition={{ duration: 1.5, repeat: Infinity }}
            />
          </div>
          <div>
            <h3 className="text-sm font-mono font-semibold text-white">
              Generating Project Guidance
            </h3>
            <p className="text-xs font-mono text-gray-400">
              {genesisStatus.stage_name || 'Processing...'} • {genesisStatus.progress_percent || 0}%
            </p>
          </div>
        </div>
        <div className="mt-3 w-full h-1.5 bg-white/10 rounded-full overflow-hidden">
          <motion.div
            className="h-full bg-gradient-to-r from-purple-400 to-cyan-400"
            initial={{ width: 0 }}
            animate={{ width: `${genesisStatus.progress_percent || 0}%` }}
            transition={{ duration: 0.5 }}
          />
        </div>
      </div>
    );
  }

  // No guidance found - offer to generate
  if (error || !guidance) {
    return (
      <div className={cn('bg-white/5 border border-cyan-400/20 p-4', className)}>
        <div className="flex items-start gap-3">
          <Sparkles className="h-5 w-5 text-cyan-400 mt-0.5" />
          <div className="flex-1">
            <h3 className="text-sm font-mono font-semibold text-white">
              Project Guidance Available
            </h3>
            <p className="text-xs font-mono text-gray-400 mt-1">
              Generate AI-powered guidance specific to your project based on your Blueprint configuration.
            </p>
            <Button
              size="sm"
              className="mt-3 h-8 text-xs bg-cyan-500/20 text-cyan-400 hover:bg-cyan-500/30 border border-cyan-500/30"
              onClick={handleTriggerGenesis}
              disabled={triggerGenesis.isPending}
            >
              {triggerGenesis.isPending ? (
                <>
                  <Loader2 className="h-3 w-3 mr-1 animate-spin" />
                  Starting...
                </>
              ) : (
                <>
                  <Sparkles className="h-3 w-3 mr-1" />
                  Generate Guidance
                </>
              )}
            </Button>
          </div>
        </div>
      </div>
    );
  }

  // Stale guidance warning
  const isStale = guidance.status === 'stale';

  return (
    <div
      className={cn(
        'bg-gradient-to-r from-purple-500/5 via-transparent to-cyan-500/5',
        'border',
        isStale ? 'border-yellow-400/30' : 'border-purple-400/20',
        className
      )}
    >
      {/* Header */}
      <button
        type="button"
        onClick={() => setExpanded(!expanded)}
        className="w-full flex items-center justify-between px-4 py-3 hover:bg-white/5 transition-colors"
      >
        <div className="flex items-center gap-3">
          <div className="relative">
            <Sparkles className="h-5 w-5 text-purple-400" />
          </div>
          <div className="text-left">
            <h3 className="text-sm font-mono font-semibold text-white flex items-center gap-2">
              {guidance.section_title || SECTION_DISPLAY_NAMES[section]}
              {isStale && (
                <span className="text-[10px] px-1.5 py-0.5 bg-yellow-500/20 text-yellow-400 rounded">
                  STALE
                </span>
              )}
            </h3>
            <p className="text-xs font-mono text-gray-400">
              {totalCount > 0 && `${completedCount}/${totalCount} tasks • `}
              Blueprint v{guidance.blueprint_version}
            </p>
          </div>
        </div>

        <div className="flex items-center gap-3">
          {/* Progress bar */}
          {totalCount > 0 && (
            <div className="hidden sm:flex items-center gap-2">
              <div className="w-20 h-1.5 bg-white/10 rounded-full overflow-hidden">
                <motion.div
                  className="h-full bg-gradient-to-r from-purple-400 to-cyan-400"
                  initial={{ width: 0 }}
                  animate={{ width: `${progressPercent}%` }}
                  transition={{ duration: 0.5, ease: 'easeOut' }}
                />
              </div>
              <span className="text-xs font-mono text-gray-400">{progressPercent}%</span>
            </div>
          )}

          {/* Expand/collapse icon */}
          {expanded ? (
            <ChevronUp className="h-4 w-4 text-gray-400" />
          ) : (
            <ChevronDown className="h-4 w-4 text-gray-400" />
          )}
        </div>
      </button>

      {/* Content */}
      <AnimatePresence>
        {expanded && (
          <motion.div
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: 'auto', opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            transition={{ duration: 0.2 }}
            className="overflow-hidden"
          >
            <div className="px-4 pb-4 space-y-4">
              {/* Description */}
              {guidance.section_description && (
                <p className="text-sm text-gray-300">
                  {guidance.section_description}
                </p>
              )}

              {/* What to Input */}
              {guidance.what_to_input && (
                <div className="bg-white/5 border border-white/10 rounded p-3">
                  <h4 className="text-xs font-mono font-semibold text-cyan-400 mb-2 flex items-center gap-1.5">
                    <Database className="h-3.5 w-3.5" />
                    What to Input
                  </h4>
                  <p className="text-xs text-gray-400 mb-2">
                    {guidance.what_to_input.description}
                  </p>
                  {guidance.what_to_input.required_items?.length > 0 && (
                    <div className="space-y-1">
                      {guidance.what_to_input.required_items.map((item, i) => (
                        <div key={i} className="flex items-center gap-2 text-xs">
                          <span className="w-1.5 h-1.5 bg-red-400 rounded-full" />
                          <span className="text-gray-300">{item}</span>
                          <span className="text-[10px] text-red-400">required</span>
                        </div>
                      ))}
                    </div>
                  )}
                  {guidance.what_to_input.optional_items?.length > 0 && (
                    <div className="space-y-1 mt-2">
                      {guidance.what_to_input.optional_items.map((item, i) => (
                        <div key={i} className="flex items-center gap-2 text-xs">
                          <span className="w-1.5 h-1.5 bg-gray-400 rounded-full" />
                          <span className="text-gray-400">{item}</span>
                          <span className="text-[10px] text-gray-500">optional</span>
                        </div>
                      ))}
                    </div>
                  )}
                </div>
              )}

              {/* Recommended Sources */}
              {guidance.recommended_sources && guidance.recommended_sources.length > 0 && (
                <div className="space-y-2">
                  <h4 className="text-xs font-mono font-semibold text-purple-400 flex items-center gap-1.5">
                    <ExternalLink className="h-3.5 w-3.5" />
                    Recommended Sources
                  </h4>
                  <div className="grid gap-2">
                    {guidance.recommended_sources.map((source, i) => (
                      <div
                        key={i}
                        className="flex items-start gap-2 p-2 bg-white/5 border border-white/10 rounded"
                      >
                        <Database className="h-3.5 w-3.5 text-gray-400 mt-0.5" />
                        <div className="flex-1 min-w-0">
                          <div className="flex items-center gap-2">
                            <span className="text-xs font-medium text-white">{source.name}</span>
                            <span
                              className={cn(
                                'text-[10px] px-1.5 py-0.5 rounded',
                                source.priority === 'required'
                                  ? 'bg-red-500/20 text-red-400'
                                  : source.priority === 'recommended'
                                  ? 'bg-yellow-500/20 text-yellow-400'
                                  : 'bg-gray-500/20 text-gray-400'
                              )}
                            >
                              {source.priority}
                            </span>
                          </div>
                          <p className="text-[10px] text-gray-500 mt-0.5">{source.description}</p>
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {/* Checklist */}
              {checklistItems.length > 0 && (
                <div className="space-y-2">
                  <h4 className="text-xs font-mono font-semibold text-green-400 flex items-center gap-1.5">
                    <CheckCircle2 className="h-3.5 w-3.5" />
                    Checklist
                  </h4>
                  <div className="space-y-1">
                    {checklistItems.map((item) => (
                      <button
                        key={item.id}
                        type="button"
                        className={cn(
                          'w-full flex items-start gap-2 p-2 rounded border transition-colors text-left',
                          item.completed
                            ? 'border-green-500/20 bg-green-500/5'
                            : 'border-white/10 bg-white/5 hover:bg-white/10'
                        )}
                        onClick={() => onChecklistToggle?.(item, !item.completed)}
                      >
                        {item.completed ? (
                          <CheckCircle2 className="h-4 w-4 text-green-400 mt-0.5" />
                        ) : (
                          <Circle className="h-4 w-4 text-gray-500 mt-0.5" />
                        )}
                        <div className="flex-1 min-w-0">
                          <span
                            className={cn(
                              'text-xs',
                              item.completed ? 'text-green-400' : 'text-white'
                            )}
                          >
                            {item.label}
                          </span>
                          {item.required && !item.completed && (
                            <span className="ml-1.5 text-[10px] text-red-400">required</span>
                          )}
                          {item.description && (
                            <p className="text-[10px] text-gray-500 mt-0.5">{item.description}</p>
                          )}
                        </div>
                      </button>
                    ))}
                  </div>
                </div>
              )}

              {/* Suggested Actions */}
              {guidance.suggested_actions && guidance.suggested_actions.length > 0 && (
                <div className="space-y-2">
                  <h4 className="text-xs font-mono font-semibold text-yellow-400 flex items-center gap-1.5">
                    <Zap className="h-3.5 w-3.5" />
                    AI-Assisted Actions
                  </h4>
                  <div className="flex flex-wrap gap-2">
                    {guidance.suggested_actions.map((action, i) => (
                      <Button
                        key={i}
                        variant="ghost"
                        size="sm"
                        className="h-7 text-xs text-yellow-400 bg-yellow-500/10 hover:bg-yellow-500/20 border border-yellow-500/20"
                        onClick={() => onActionClick?.(action)}
                      >
                        <Sparkles className="h-3 w-3 mr-1" />
                        {action.label}
                      </Button>
                    ))}
                  </div>
                </div>
              )}

              {/* Tips */}
              {guidance.tips && guidance.tips.length > 0 && (
                <div className="bg-yellow-500/5 border border-yellow-500/20 rounded p-3">
                  <h4 className="text-xs font-mono font-semibold text-yellow-400 mb-2 flex items-center gap-1.5">
                    <Lightbulb className="h-3.5 w-3.5" />
                    Tips
                  </h4>
                  <ul className="space-y-1">
                    {guidance.tips.map((tip, i) => (
                      <li key={i} className="text-xs text-gray-400 flex items-start gap-2">
                        <span className="text-yellow-400">•</span>
                        {tip}
                      </li>
                    ))}
                  </ul>
                </div>
              )}

              {/* Provenance */}
              {showProvenance && (
                <div className="flex items-center justify-between pt-2 border-t border-white/10">
                  <div className="flex items-center gap-2 text-[10px] text-gray-500">
                    <Info className="h-3 w-3" />
                    <span>
                      Generated from Blueprint v{guidance.blueprint_version}
                      {guidance.created_at && (
                        <span className="ml-1">
                          • {new Date(guidance.created_at).toLocaleDateString()}
                        </span>
                      )}
                    </span>
                  </div>
                  <Button
                    variant="ghost"
                    size="sm"
                    className="h-6 text-[10px] text-gray-500 hover:text-white"
                    onClick={handleRegenerate}
                    disabled={regenerateGuidance.isPending}
                  >
                    {regenerateGuidance.isPending ? (
                      <Loader2 className="h-3 w-3 animate-spin" />
                    ) : (
                      <>
                        <RefreshCw className="h-3 w-3 mr-1" />
                        Regenerate
                      </>
                    )}
                  </Button>
                </div>
              )}
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}

export default ProjectGuidancePanel;
