"""
Project Guidance Model (Slice 2C: Project Genesis)
Reference: blueprint.md §7 - Section Guidance

Stores AI-generated, project-specific guidance for each workspace section.
Generated by the PROJECT_GENESIS PIL job based on the finalized Blueprint v2.

Lifecycle:
- Created when project is finalized (status DRAFT -> ACTIVE)
- Regenerated when blueprint changes (tracks version history)
- Each section stores: what_to_input, recommended_sources, checklist, suggested_actions
"""

import uuid
from datetime import datetime
from enum import Enum
from typing import TYPE_CHECKING, Any, Dict, List, Optional

from sqlalchemy import (
    Boolean,
    DateTime,
    ForeignKey,
    Integer,
    String,
    Text,
    UniqueConstraint,
)
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.session import Base

if TYPE_CHECKING:
    from app.models.blueprint import Blueprint
    from app.models.project_spec import ProjectSpec


# ============================================================================
# Project Guidance Sections (maps to workspace pages)
# ============================================================================

class GuidanceSection(str, Enum):
    """Workspace sections that receive project-specific guidance."""
    # Data & Input sections
    DATA = "data"
    PERSONAS = "personas"

    # Configuration sections
    RULES = "rules"
    RUN_PARAMS = "run_params"

    # Scenario sections
    EVENT_LAB = "event_lab"
    SCENARIO_LAB = "scenario_lab"

    # Validation sections
    CALIBRATE = "calibrate"
    BACKTEST = "backtest"
    RELIABILITY = "reliability"

    # Execution sections
    RUN = "run"
    PREDICT = "predict"

    # Analysis sections
    UNIVERSE_MAP = "universe_map"
    REPORTS = "reports"


class GuidanceStatus(str, Enum):
    """Status of guidance generation."""
    PENDING = "pending"       # Job queued
    GENERATING = "generating" # Job running
    READY = "ready"          # Guidance available
    STALE = "stale"          # Blueprint changed, needs regeneration
    FAILED = "failed"        # Generation failed


# ============================================================================
# ProjectGuidance Model
# ============================================================================

class ProjectGuidance(Base):
    """
    Project-specific AI guidance for workspace sections.

    Generated by the PROJECT_GENESIS job based on:
    - Blueprint v2 configuration (goal, core type, temporal mode)
    - Selected settings (core_strategy, temporal_settings)
    - Domain-specific recommendations

    Each section receives tailored guidance including:
    - what_to_input: Description of required/recommended data
    - recommended_sources: Suggested data sources
    - checklist: Actionable items to complete
    - suggested_actions: Available AI-assisted actions
    - provenance: Link to the generating job for audit
    """
    __tablename__ = "project_guidance"
    __table_args__ = (
        UniqueConstraint(
            'project_id', 'blueprint_version', 'section',
            name='uq_project_guidance_version_section'
        ),
    )

    # Identity
    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4
    )
    tenant_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("tenants.id", ondelete="CASCADE"),
        nullable=False,
        index=True
    )
    project_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("project_specs.id", ondelete="CASCADE"),
        nullable=False,
        index=True
    )
    blueprint_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("blueprints.id", ondelete="SET NULL"),
        nullable=True,
        index=True
    )

    # Versioning for audit
    blueprint_version: Mapped[int] = mapped_column(
        Integer, nullable=False, default=1
    )
    guidance_version: Mapped[int] = mapped_column(
        Integer, nullable=False, default=1
    )

    # Section identification
    section: Mapped[str] = mapped_column(
        String(50), nullable=False, index=True
    )

    # Status
    status: Mapped[str] = mapped_column(
        String(50), default=GuidanceStatus.PENDING.value, nullable=False
    )

    # Guidance content (AI-generated)
    section_title: Mapped[str] = mapped_column(
        String(255), nullable=False, default=""
    )
    section_description: Mapped[Optional[str]] = mapped_column(
        Text, nullable=True
    )

    # What to input for this section
    what_to_input: Mapped[Optional[Dict[str, Any]]] = mapped_column(
        JSONB, nullable=True
    )  # {description: str, required_items: [], optional_items: []}

    # Recommended data sources
    recommended_sources: Mapped[Optional[List[Dict[str, Any]]]] = mapped_column(
        JSONB, nullable=True
    )  # [{name: str, type: str, description: str, priority: str}]

    # Checklist items for this section
    checklist: Mapped[Optional[List[Dict[str, Any]]]] = mapped_column(
        JSONB, nullable=True
    )  # [{id: str, label: str, description: str, required: bool, completed: bool}]

    # Suggested actions (AI-assisted)
    suggested_actions: Mapped[Optional[List[Dict[str, Any]]]] = mapped_column(
        JSONB, nullable=True
    )  # [{action_type: str, label: str, description: str, endpoint: str}]

    # Additional context/tips
    tips: Mapped[Optional[List[str]]] = mapped_column(
        JSONB, nullable=True
    )  # List of helpful tips for this section

    # Slice 2D: Blueprint traceability (proves guidance is derived from blueprint)
    project_fingerprint: Mapped[Optional[Dict[str, Any]]] = mapped_column(
        JSONB, nullable=True
    )  # {goal_hash: str, domain: str, core_strategy: str, blueprint_version: int}
    source_refs: Mapped[Optional[List[str]]] = mapped_column(
        JSONB, nullable=True
    )  # List of blueprint fields used: ["goal_text", "domain_guess", "horizon.start_date", ...]

    # Provenance (audit trail)
    job_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("pil_jobs.id", ondelete="SET NULL"),
        nullable=True
    )
    artifact_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("pil_artifacts.id", ondelete="SET NULL"),
        nullable=True
    )
    llm_call_id: Mapped[Optional[str]] = mapped_column(
        String(100), nullable=True
    )  # For LLM provenance tracking

    # Slice 2D: Full LLM provenance (provider, model, cache status, etc.)
    llm_proof: Mapped[Optional[Dict[str, Any]]] = mapped_column(
        JSONB, nullable=True
    )  # {provider: str, model: str, cache: "hit"|"bypassed", fallback: bool, request_id: str}

    # Active flag (only one active per project+section)
    is_active: Mapped[bool] = mapped_column(
        Boolean, default=True, nullable=False
    )

    # Timestamps
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=datetime.utcnow, nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=datetime.utcnow, onupdate=datetime.utcnow,
        nullable=False
    )

    # Relationships
    project: Mapped["ProjectSpec"] = relationship(
        "ProjectSpec",
        foreign_keys=[project_id]
    )
    blueprint: Mapped[Optional["Blueprint"]] = relationship(
        "Blueprint",
        foreign_keys=[blueprint_id]
    )

    def __repr__(self) -> str:
        return f"<ProjectGuidance {self.id} project={self.project_id} section={self.section}>"

    def to_dict(self) -> Dict[str, Any]:
        """Return dictionary representation."""
        return {
            "id": str(self.id),
            "tenant_id": str(self.tenant_id),
            "project_id": str(self.project_id),
            "blueprint_id": str(self.blueprint_id) if self.blueprint_id else None,
            "blueprint_version": self.blueprint_version,
            "guidance_version": self.guidance_version,
            "section": self.section,
            "status": self.status,
            "section_title": self.section_title,
            "section_description": self.section_description,
            "what_to_input": self.what_to_input,
            "recommended_sources": self.recommended_sources,
            "checklist": self.checklist,
            "suggested_actions": self.suggested_actions,
            "tips": self.tips,
            "project_fingerprint": self.project_fingerprint,
            "source_refs": self.source_refs,
            "job_id": str(self.job_id) if self.job_id else None,
            "artifact_id": str(self.artifact_id) if self.artifact_id else None,
            "llm_call_id": self.llm_call_id,
            "llm_proof": self.llm_proof,
            "is_active": self.is_active,
            "created_at": self.created_at.isoformat() if self.created_at else None,
            "updated_at": self.updated_at.isoformat() if self.updated_at else None,
        }


# ============================================================================
# Section Configuration (maps sections to workspace pages)
# ============================================================================

GUIDANCE_SECTION_CONFIG = {
    GuidanceSection.DATA: {
        "title": "Data Sources",
        "page_route": "/data",
        "default_description": "Upload or connect your data sources.",
    },
    GuidanceSection.PERSONAS: {
        "title": "Personas",
        "page_route": "/personas",
        "default_description": "Define the population or agents for simulation.",
    },
    GuidanceSection.RULES: {
        "title": "Rules & Assumptions",
        "page_route": "/rules",
        "default_description": "Configure business rules and simulation assumptions.",
    },
    GuidanceSection.RUN_PARAMS: {
        "title": "Run Parameters",
        "page_route": "/run-params",
        "default_description": "Set simulation parameters and constraints.",
    },
    GuidanceSection.EVENT_LAB: {
        "title": "Event Lab",
        "page_route": "/event-lab",
        "default_description": "Create and manage what-if scenarios.",
    },
    GuidanceSection.SCENARIO_LAB: {
        "title": "Scenario Lab",
        "page_route": "/scenario-lab",
        "default_description": "Build complex multi-event scenarios.",
    },
    GuidanceSection.CALIBRATE: {
        "title": "Calibration",
        "page_route": "/calibrate",
        "default_description": "Tune model parameters against ground truth.",
    },
    GuidanceSection.BACKTEST: {
        "title": "Backtesting",
        "page_route": "/backtest",
        "default_description": "Validate predictions against historical data.",
    },
    GuidanceSection.RELIABILITY: {
        "title": "Reliability",
        "page_route": "/reliability",
        "default_description": "Assess prediction confidence and stability.",
    },
    GuidanceSection.RUN: {
        "title": "Run Center",
        "page_route": "/run-center",
        "default_description": "Execute and monitor simulations.",
    },
    GuidanceSection.PREDICT: {
        "title": "Predictions",
        "page_route": "/predict",
        "default_description": "View and analyze prediction outcomes.",
    },
    GuidanceSection.UNIVERSE_MAP: {
        "title": "Universe Map",
        "page_route": "/universe-map",
        "default_description": "Explore the simulation node graph.",
    },
    GuidanceSection.REPORTS: {
        "title": "Reports & Exports",
        "page_route": "/reports",
        "default_description": "Generate and export analysis reports.",
    },
}
