/**
 * Node & Edge Contracts (Universe Map)
 * Reference: project.md §6.7
 *
 * Node is a parallel-universe snapshot.
 * Edge is a transformation from one node to another.
 */

import {
  ArtifactRef,
  ConfidenceLevel,
  Timestamps,
  TenantScoped
} from './common';

// ============================================================================
// Aggregated Outcome (summary of run results)
// ============================================================================

export interface AggregatedOutcome {
  // Primary prediction
  primary_outcome: string;
  primary_outcome_probability: number;

  // Full distribution (outcome -> probability)
  outcome_distribution: Record<string, number>;

  // Key metrics
  key_metrics: {
    metric_name: string;
    value: number;
    unit?: string;
    trend?: 'increasing' | 'stable' | 'decreasing';
  }[];

  // Variance across runs (if multi-seed)
  variance_metrics?: Record<string, number>;

  // Summary text (generated)
  summary_text?: string;
}

// ============================================================================
// Node Confidence
// ============================================================================

export interface NodeConfidence {
  confidence_level: ConfidenceLevel;
  confidence_score: number;  // 0-1

  // Breakdown of confidence factors
  factors: {
    factor_name: string;
    score: number;
    weight: number;
    notes?: string;
  }[];

  // Reference to full reliability report
  reliability_ref?: ArtifactRef;
}

// ============================================================================
// Node (project.md §6.7)
// ============================================================================

export interface Node extends TenantScoped, Timestamps {
  // Identity
  node_id: string;
  project_id: string;

  // Tree structure
  parent_node_id?: string;  // null for root node
  depth: number;            // 0 for root

  // Scenario definition
  scenario_patch_ref?: ArtifactRef;  // What changed to create this branch

  // Runs associated with this node
  run_refs: ArtifactRef[];  // 1+ runs (aggregated)

  // Outcomes
  aggregated_outcome?: AggregatedOutcome;

  // Probability (conditional to parent)
  probability: number;       // 0-1, P(this | parent)
  cumulative_probability: number;  // Product of probabilities to root

  // Confidence/reliability
  confidence: NodeConfidence;

  // Telemetry for replay
  telemetry_ref?: ArtifactRef;

  // Clustering
  cluster_id?: string;      // If part of a cluster
  is_cluster_representative: boolean;

  // UI state (not authoritative, just hints)
  ui_position?: {
    x: number;
    y: number;
  };
  is_collapsed: boolean;
  is_pinned: boolean;

  // Metadata
  label?: string;
  description?: string;
  tags?: string[];

  // Status
  is_baseline: boolean;     // Is this the root baseline?
  is_explored: boolean;     // Has user examined this node?
  child_count: number;
}

// ============================================================================
// Edge Intervention
// ============================================================================

export interface EdgeIntervention {
  intervention_type: 'event_script' | 'variable_delta' | 'nl_query' | 'expansion';

  // Reference to the intervention artifact
  event_script_ref?: ArtifactRef;
  variable_deltas?: Record<string, unknown>;
  nl_query?: string;

  // For expansion-generated edges
  expansion_strategy?: 'user_ask' | 'auto_explore' | 'sensitivity';
}

// ============================================================================
// Edge Explanation
// ============================================================================

export interface EdgeExplanation {
  // Short label
  short_label: string;

  // Full explanation text
  explanation_text: string;

  // Key factors that differentiate this branch
  key_differentiators: string[];

  // Generated by
  generated_by: 'compiler' | 'system' | 'user';
}

// ============================================================================
// Edge (project.md §6.7)
// ============================================================================

export interface Edge extends TenantScoped, Timestamps {
  // Identity
  edge_id: string;
  project_id: string;

  // Connections
  from_node_id: string;
  to_node_id: string;

  // What created this edge
  intervention: EdgeIntervention;

  // Why this edge exists
  explanation: EdgeExplanation;

  // Metadata
  is_primary_path: boolean;  // Part of most likely path
  weight?: number;           // Optional weight for visualization
}

// ============================================================================
// Node Cluster (for progressive expansion)
// ============================================================================

export interface NodeCluster {
  cluster_id: string;
  project_id: string;

  // Cluster properties
  label: string;
  description?: string;

  // Member nodes
  member_node_ids: string[];
  representative_node_id: string;

  // Aggregated cluster outcome
  cluster_outcome?: AggregatedOutcome;
  cluster_probability: number;

  // Expansion state
  is_expanded: boolean;
  expandable: boolean;

  // UI position
  ui_position?: {
    x: number;
    y: number;
  };
}

// ============================================================================
// Universe Map State (for frontend)
// ============================================================================

export interface UniverseMapState {
  project_id: string;

  // Root reference
  root_node_id: string;

  // Visible nodes and edges (respecting collapse state)
  visible_nodes: string[];
  visible_edges: string[];
  visible_clusters: string[];

  // Selected state
  selected_node_id?: string;
  compared_node_ids?: string[];

  // View state
  zoom_level: number;
  viewport_center: { x: number; y: number };

  // Filters active
  probability_threshold: number;
  show_low_confidence: boolean;
}

// ============================================================================
// Create/Update DTOs
// ============================================================================

export interface CreateNodeInput {
  project_id: string;
  parent_node_id?: string;
  scenario_patch_ref?: ArtifactRef;
  label?: string;
  description?: string;
  tags?: string[];
}

export interface CreateEdgeInput {
  project_id: string;
  from_node_id: string;
  to_node_id: string;
  intervention: EdgeIntervention;
  explanation?: Partial<EdgeExplanation>;
}

export interface ExpandNodeInput {
  node_id: string;
  expansion_type: 'ask' | 'explore' | 'sensitivity';

  // For ask expansion
  nl_query?: string;

  // For explore expansion
  num_branches?: number;

  // For sensitivity expansion
  sensitivity_variables?: string[];
}

export interface ClusterNodesInput {
  project_id: string;
  node_ids: string[];
  label: string;
  description?: string;
}

// ============================================================================
// Node/Edge Summaries (for lists)
// ============================================================================

export interface NodeSummary {
  node_id: string;
  parent_node_id?: string;
  label?: string;
  probability: number;
  confidence_level: ConfidenceLevel;
  is_baseline: boolean;
  has_outcome: boolean;
  child_count: number;
  created_at: string;
}

export interface EdgeSummary {
  edge_id: string;
  from_node_id: string;
  to_node_id: string;
  short_label: string;
  intervention_type: EdgeIntervention['intervention_type'];
}

// ============================================================================
// Path Analysis
// ============================================================================

export interface PathAnalysis {
  path_id: string;

  // Ordered list of nodes in path
  node_sequence: string[];

  // Path probability (product of edge probabilities)
  path_probability: number;

  // Path summary
  summary: string;
  key_events: string[];

  // Comparison data
  final_outcome: AggregatedOutcome;
}

export interface MostLikelyPaths {
  project_id: string;
  paths: PathAnalysis[];
  computed_at: string;
}
